### PR TITLE
Friendshipsv2

### PR DESCRIPTION
**Pull request by ashraffares**
implement friendships with 2 rows for mutual friendship.
- On accept method add newly recorded for friend
- so it will save in database fares is friend with billo and billo is friend with fares

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

- [x] Remove add friend button once you send a friendship request not when it is accepted

- [x] There is no button to accept a friend request from all users page

- [x] Instead of processing objects in application memory, let's define association with SQL query.

      # pending_friends
      has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
      has_many :pending_friends, through: :pending_friendships, source: :friend

      # friend_requests
      has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
      has_many :friend_requests, through: :inverted_friendships

## OPTIONAL



 Kindly write more tests also for controllers

Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by ashraffares** [comment]
@MkrtichSargsyan 
-Remove add Friend when the request is sent
-Add button to accept and reject a request from the index
-Add more association peding_friends and friend_requests

**Review by henatan99 — APPROVED** [review]
# Project Approved :100:  

### Hi there, you did a really nice work on this milestone. Congratulations!!! :clap: :champagne: :partying_face: 

## To Highlight 
- Thank you for implementing the requested changes by the previous review
- Your app satisfies the project's milestone requirements.
- CRUD actions are well implemented.
- Unit tests are representative and working well.  
You can implement the below optional improvements which are not required for submission of your project.

## OPTIONAL Improvements 
- Try to implement logic methods in the models as much as possible. 
- Try to implement integrations tests too
- Check if your app addresses the N+1 query problem, just browse about it and evaluate your app. 

### You can now emerge the PR and submit the mandatory project completion form.

If you have any query, reach out to me via:
[LinkedIn](https://www.linkedin.com/in/henok-mekonnen/) | [Twitter](https://twitter.com/henatan99) | Henok Mekonnen on Slack 

## Happy Coding :computer:

**Comment by ashraffares** [comment]
https://intense-ocean-78406.herokuapp.com/users/sign_in

**Review by oloomoses — COMMENTED** [review]
# Congratulations, Milestone: deploy Approved :muscle: :tada: :clamp: 
**Well done for the hard work you have put into this project to its completion :muscle: .**
**I wish you the best of luck in your next project and see you at the top :rocket:** 

Slack: _Oloo Moses_

**Pull request merged**
